// Copyright (C) 2026 Mouiz Ahmed
// SPDX-License-Identifier: AGPL-3.0-only

package sshconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mouizahmed/sshstate/internal/paths"
)

const Header = `# Generated by sshstate. Do not edit: this file is rewritten from the vault.
# Managed hosts, options, and trust come from ` + "`sshstate`" + ` commands.
`

type Identity struct {
	Slot      int
	Digest    string
	PublicKey string
}

type Host struct {
	Alias      string
	HostName   string
	User       string
	Port       int
	ProxyJump  *string
	Identities []Identity
}

func (h Host) PublicFileName(id Identity) string {
	return fmt.Sprintf("%s-%02d-%s.pub", h.Alias, id.Slot, id.Digest)
}

func Render(hosts []Host, l paths.Layout) (string, error) {
	sorted := append([]Host(nil), hosts...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Alias < sorted[j].Alias })

	var b strings.Builder
	b.WriteString(Header)

	for _, h := range sorted {
		if err := checkRenderable(h); err != nil {
			return "", err
		}
		b.WriteString("\nHost ")
		b.WriteString(h.Alias)
		b.WriteString("\n")
		fmt.Fprintf(&b, "    HostName %s\n", h.HostName)
		fmt.Fprintf(&b, "    User %s\n", h.User)
		fmt.Fprintf(&b, "    Port %d\n", h.Port)
		if h.ProxyJump != nil {
			fmt.Fprintf(&b, "    ProxyJump %s\n", *h.ProxyJump)
		} else {
			b.WriteString("    ProxyJump none\n")
		}
		fmt.Fprintf(&b, "    IdentityAgent %s\n", l.AgentSocket())
		for _, id := range h.Identities {
			fmt.Fprintf(&b, "    IdentityFile %s\n", filepath.Join(l.PublicDir(), h.PublicFileName(id)))
		}
		b.WriteString("    IdentitiesOnly yes\n")
		b.WriteString("    ForwardAgent no\n")
		b.WriteString("    StrictHostKeyChecking ask\n")
		b.WriteString("    UpdateHostKeys no\n")
		fmt.Fprintf(&b, "    UserKnownHostsFile %s %s\n", l.CaptureFile(), l.KnownHosts())
	}
	return b.String(), nil
}

func checkRenderable(h Host) error {
	for field, value := range map[string]string{
		"alias":    h.Alias,
		"hostname": h.HostName,
		"user":     h.User,
	} {
		if value == "" {
			return fmt.Errorf("host %q has no %s", h.Alias, field)
		}
		if strings.ContainsAny(value, "\n\r \t") {
			return fmt.Errorf("host %q has whitespace in %s", h.Alias, field)
		}
	}
	if h.Port < 1 || h.Port > 65535 {
		return fmt.Errorf("host %q has port %d", h.Alias, h.Port)
	}
	if h.ProxyJump != nil && strings.ContainsAny(*h.ProxyJump, "\n\r \t") {
		return fmt.Errorf("host %q has whitespace in ProxyJump", h.Alias)
	}
	seen := map[int]bool{}
	for _, id := range h.Identities {
		if id.Slot < 1 {
			return fmt.Errorf("host %q has an identity in slot %d", h.Alias, id.Slot)
		}
		if seen[id.Slot] {
			return fmt.Errorf("host %q has two identities in slot %d", h.Alias, id.Slot)
		}
		seen[id.Slot] = true
		if len(id.Digest) != 64 {
			return fmt.Errorf("host %q identity %d has a %d-character digest, want 64 hex", h.Alias, id.Slot, len(id.Digest))
		}
	}
	return nil
}

func Publish(hosts []Host, l paths.Layout) error {
	if err := os.MkdirAll(l.PublicDir(), 0o700); err != nil {
		return fmt.Errorf("create public key directory: %w", err)
	}
	for _, h := range hosts {
		for _, id := range h.Identities {
			path := filepath.Join(l.PublicDir(), h.PublicFileName(id))
			body := strings.TrimRight(id.PublicKey, "\n") + "\n"
			if err := atomicWrite(path, []byte(body), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", filepath.Base(path), err)
			}
		}
	}
	text, err := Render(hosts, l)
	if err != nil {
		return err
	}
	if err := atomicWrite(l.Config(), []byte(text), 0o600); err != nil {
		return fmt.Errorf("write generated config: %w", err)
	}
	return nil
}

func ObsoletePublicFiles(hosts []Host, l paths.Layout) ([]string, error) {
	wanted := map[string]bool{}
	for _, h := range hosts {
		for _, id := range h.Identities {
			wanted[h.PublicFileName(id)] = true
		}
	}
	entries, err := os.ReadDir(l.PublicDir())
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var stale []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".pub") {
			continue
		}
		if !wanted[e.Name()] {
			stale = append(stale, filepath.Join(l.PublicDir(), e.Name()))
		}
	}
	sort.Strings(stale)
	return stale, nil
}
