// Copyright (C) 2026 Mouiz Ahmed
// SPDX-License-Identifier: AGPL-3.0-only

package sshconfig

import (
	"fmt"
	"os"
	"strings"

	"github.com/mouizahmed/sshstate/internal/paths"
)

const KnownHostsHeader = `# Generated by sshstate. Do not edit: this file is rewritten from the vault.
# New host keys accepted by OpenSSH are written to known_hosts.capture instead,
# which sshstate reads and never rewrites.
`

func PublishKnownHosts(lines []string, l paths.Layout) error {
	var b strings.Builder
	b.WriteString(KnownHostsHeader)
	for _, line := range lines {
		if strings.ContainsAny(line, "\n\r") {
			return fmt.Errorf("known_hosts line contains a newline: %q", line)
		}
		b.WriteString(strings.TrimSpace(line))
		b.WriteString("\n")
	}
	if err := atomicWrite(l.KnownHosts(), []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write generated known_hosts: %w", err)
	}
	return EnsureCaptureFile(l)
}

func EnsureCaptureFile(l paths.Layout) error {
	if err := os.MkdirAll(l.SSH, 0o700); err != nil {
		return err
	}
	f, err := os.OpenFile(l.CaptureFile(), os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("create capture file: %w", err)
	}
	return f.Close()
}
